<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class MasterCafeFullMenuSeeder extends Seeder
{
    /**
     * Seed seluruh menu fisik Master Cafe berdasarkan lembar foto buku menu resmi.
     */
    public function run(): void
    {
        if (!Schema::hasColumn('menu', 'sub_kategori')) {
            return;
        }

        $menus = [
            // ==========================================
            // 1. MAKANAN: SEAFOOD & IKAN (HALAMAN 1)
            // ==========================================
            [
                'nama_menu' => 'Udang Goreng Petai',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 60000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Udang segar digoreng gurih berpadu petai renyah dan sambal khas Master Cafe.',
            ],
            [
                'nama_menu' => 'Udang Goreng Tepung',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 60000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Udang segar berbalut tepung bumbu krispi renyah disajikan dengan saus cocolan.',
            ],
            [
                'nama_menu' => 'Udang Korea',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 60000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Udang renyah berlumur saus manis pedas gurih khas saus Korea.',
            ],
            [
                'nama_menu' => 'Udang Mentega',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 60000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Udang tumis saus mentega wangi gurih dengan irisan bawang bombay.',
            ],
            [
                'nama_menu' => 'Udang Asam Pedas',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 60000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Udang segar dimasak kuah asam pedas kental menggugah selera.',
            ],
            [
                'nama_menu' => 'Ikan Tenggiri Asam Pedas',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 0,
                'is_dynamic_price' => true,
                'deskripsi' => 'Ikan tenggiri segar kuah asam pedas kaya rempah (Harga sesuai berat timbangan ikan).',
            ],
            [
                'nama_menu' => 'Lele Goreng + Nasi',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 23000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Ikan lele goreng renyah disajikan lengkap dengan nasi putih hangat, sambal, dan lalapan.',
            ],
            [
                'nama_menu' => 'Sea Food Tumpah',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 35000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Pesta aneka hidangan laut melimpah dengan saus spesial Master Cafe (Pilihan porsi 1 orang, 2 orang, 4 orang).',
            ],
            [
                'nama_menu' => 'Cumi Goreng Tepung',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 60000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Cumi-cumi segar goreng tepung keemasan yang renyah dan empuk di dalam.',
            ],
            [
                'nama_menu' => 'Ikan Senangin Asam Manis / Asam Pedas',
                'kategori' => 'makanan',
                'sub_kategori' => 'Seafood & Ikan',
                'harga' => 0,
                'is_dynamic_price' => true,
                'deskripsi' => 'Ikan senangin segar dengan pilihan kuah asam manis atau asam pedas (Harga sesuai berat timbangan ikan).',
            ],

            // ==========================================
            // 2. MAKANAN: OLAHAN AYAM (HALAMAN 1)
            // ==========================================
            [
                'nama_menu' => 'Ayam Geprek Cabe Ijo + Nasi',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 35000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Ayam goreng krispi ditumbuk dengan sambal cabai hijau segar pedas gurih lengkap dengan nasi putih.',
            ],
            [
                'nama_menu' => 'Ayam Goreng Cabe Ijo + Nasi',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 25000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Ayam goreng bumbu tradisional disiram sambal cabai hijau dan nasi putih hangat.',
            ],
            [
                'nama_menu' => 'Ayam Porsi Cabe Ijo',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 30000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Porsi ayam goreng gurih berlumur sambal cabai hijau spesial tanpa nasi.',
            ],
            [
                'nama_menu' => 'Ayam Porsi Cabe Merah',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 30000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Porsi ayam goreng gurih berlumur sambal cabai merah pedas mantap tanpa nasi.',
            ],
            [
                'nama_menu' => 'Ayam Goreng Cabe Merah + Nasi',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 25000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Ayam goreng empuk disiram ulekan sambal cabai merah pedas nampol disajikan dengan nasi.',
            ],
            [
                'nama_menu' => 'Ayam Geprek Cabe Merah + Nasi',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 35000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Ayam krispi digeprek sambal cabai merah segar berpadu nasi putih pulen.',
            ],
            [
                'nama_menu' => 'Ayam Penyet',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 25000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Ayam goreng gurih dipenyet di atas cobek sambal terasi harum menggugah selera.',
            ],
            [
                'nama_menu' => 'Ayam Goreng Mentega Saus Merah / Hitam',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 35000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Potongan ayam goreng saus mentega lezat dengan pilihan saus merah manis asam atau saus lada hitam.',
            ],
            [
                'nama_menu' => 'Ayam Bakar',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 25000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Ayam bakar beraroma khas dengan olesan bumbu manis gurih meresap sampai ke tulang.',
            ],
            [
                'nama_menu' => 'Chicken Katsu + Nasi',
                'kategori' => 'makanan',
                'sub_kategori' => 'Olahan Ayam',
                'harga' => 30000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Fillet dada ayam goreng tepung roti renyah disajikan dengan nasi putih dan saus spesial.',
            ],

            // ==========================================
            // 3. MAKANAN: SAYUR & LAUK (HALAMAN 1)
            // ==========================================
            [
                'nama_menu' => 'Perkedel Jagung',
                'kategori' => 'makanan',
                'sub_kategori' => 'Sayur & Lauk',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Bakwan jagung manis renyah keemasan, camilan dan pendamping lauk favorit.',
            ],
            [
                'nama_menu' => 'Cah Kangkung',
                'kategori' => 'makanan',
                'sub_kategori' => 'Sayur & Lauk',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Tumisan kangkung hijau segar dimasak cepat dengan bawang putih dan bumbu gurih.',
            ],
            [
                'nama_menu' => 'Kangkung Trasi',
                'kategori' => 'makanan',
                'sub_kategori' => 'Sayur & Lauk',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kangkung segar ditumis dengan racikan terasi udang dan irisan cabai merah harum.',
            ],
            [
                'nama_menu' => 'Capcai',
                'kategori' => 'makanan',
                'sub_kategori' => 'Sayur & Lauk',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Aneka ragam sayuran segar ditumis dengan kuah gurih dan irisan bakso sedap.',
            ],
            [
                'nama_menu' => 'Tempe Goreng',
                'kategori' => 'makanan',
                'sub_kategori' => 'Sayur & Lauk',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Tempe kedelai gurih digoreng kecokelatan renyah di luar lembut di dalam.',
            ],
            [
                'nama_menu' => 'Telor Dadar',
                'kategori' => 'makanan',
                'sub_kategori' => 'Sayur & Lauk',
                'harga' => 12000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Telur dadar tebal gurih beraroma daun bawang kecokelatan harum.',
            ],
            [
                'nama_menu' => 'Hati & Ampela Goreng',
                'kategori' => 'makanan',
                'sub_kategori' => 'Sayur & Lauk',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Hati dan ampela ayam bumbu rempah kuning digoreng gurih empuk.',
            ],

            // ==========================================
            // 4. MAKANAN: NASI GORENG (HALAMAN 2)
            // ==========================================
            [
                'nama_menu' => 'Nasi Goreng Merah Spesial',
                'kategori' => 'makanan',
                'sub_kategori' => 'Nasi Goreng',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Nasi goreng saus merah khas racikan Master Cafe dengan telur dan topping komplit.',
            ],
            [
                'nama_menu' => 'Nasi Goreng Merah',
                'kategori' => 'makanan',
                'sub_kategori' => 'Nasi Goreng',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Nasi goreng saus merah gurih manis dengan telur dan kerupuk.',
            ],
            [
                'nama_menu' => 'Nasi Goreng Hijau Spesial',
                'kategori' => 'makanan',
                'sub_kategori' => 'Nasi Goreng',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Nasi goreng bumbu cabai hijau harum kaya rempah disajikan dengan topping komplit.',
            ],
            [
                'nama_menu' => 'Nasi Goreng Hijau',
                'kategori' => 'makanan',
                'sub_kategori' => 'Nasi Goreng',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Nasi goreng bumbu cabai hijau gurih segar dengan telur dan lalapan.',
            ],
            [
                'nama_menu' => 'Nasi Goreng Kampung Spesial',
                'kategori' => 'makanan',
                'sub_kategori' => 'Nasi Goreng',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Nasi goreng bumbu kampung otentik dengan irisan ayam, telur dadar, dan kerupuk renyah.',
            ],
            [
                'nama_menu' => 'Nasi Goreng Kampung',
                'kategori' => 'makanan',
                'sub_kategori' => 'Nasi Goreng',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Nasi goreng kampung bumbu gurih tradisional lezat.',
            ],
            [
                'nama_menu' => 'Nasi Goreng Petai',
                'kategori' => 'makanan',
                'sub_kategori' => 'Nasi Goreng',
                'harga' => 28000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Nasi goreng harum berpadu butiran petai segar yang gurih dan sedap.',
            ],

            // ==========================================
            // 5. MAKANAN: MIE & PASTA (HALAMAN 2)
            // ==========================================
            [
                'nama_menu' => 'Mie Sagu Cabe Merah Komplit',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Mie sagu kenyal khas Selatpanjang dengan bumbu cabai merah pedas dan topping komplit.',
            ],
            [
                'nama_menu' => 'Mie Sagu Cabe Merah',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Mie sagu kenyal bumbu cabai merah gurih lezat.',
            ],
            [
                'nama_menu' => 'Mie Sagu Cabe Hijau Komplit',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Mie sagu khas bumbu cabai hijau gurih segar dengan isian komplit.',
            ],
            [
                'nama_menu' => 'Mie Sagu Cabe Hijau',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Mie sagu kenyal gurih bumbu cabai hijau segar.',
            ],
            [
                'nama_menu' => 'Mie Kuning Rebus',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Mie kuning kuah kaldu hangat gurih berpadu telur rebus dan sayur sawi segar.',
            ],
            [
                'nama_menu' => 'Mie Kuning Goreng Komplit',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Mie kuning goreng bumbu rempah nikmat dengan isian telur, bakso, dan sayur komplit.',
            ],
            [
                'nama_menu' => 'Mie Kuning Goreng',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Mie kuning goreng kecap manis gurih dengan telur dan sayuran.',
            ],
            [
                'nama_menu' => 'Mie Tiau Komplit',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kwetiau goreng kenyal gurih beraroma smoky dengan topping sayur, telur, dan bakso.',
            ],
            [
                'nama_menu' => 'Mie Tiau',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kwetiau goreng bumbu gurih nikmat dengan sayuran segar.',
            ],
            [
                'nama_menu' => 'Mi Bihun',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Bihun goreng lembut disajikan dengan telur, bumbu gurih harum, dan acar segar.',
            ],
            [
                'nama_menu' => 'Indomie Rebus / Rebus Pedas',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Indomie kuah hangat disajikan dengan telur dan sawi segar (Bisa pilih versi original atau pedas).',
            ],
            [
                'nama_menu' => 'Indomie Goreng / Goreng Pedas',
                'kategori' => 'makanan',
                'sub_kategori' => 'Mie & Pasta',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Indomie goreng lezat disajikan dengan telur mata sapi dan taburan bawang renyah.',
            ],

            // ==========================================
            // 6. MAKANAN: SPESIAL & MENU BARU (HAL 2 & 3)
            // ==========================================
            [
                'nama_menu' => 'Seblak',
                'kategori' => 'makanan',
                'sub_kategori' => 'Spesial & Menu Baru',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Seblak kuah kencur pedas beraroma sedap dengan aneka kerupuk kenyal dan topping telur.',
            ],
            [
                'nama_menu' => 'Tom Yam',
                'kategori' => 'makanan',
                'sub_kategori' => 'Spesial & Menu Baru',
                'harga' => 25000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Sup kuah asam pedas khas Thailand dengan isian seafood segar, jamur, dan serai harum.',
            ],
            [
                'nama_menu' => 'Sop Ayam Kampung',
                'kategori' => 'makanan',
                'sub_kategori' => 'Spesial & Menu Baru',
                'harga' => 35000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Sup kaldu ayam kampung bening kaya rempah dengan potongan daging ayam empuk dan sayuran segar.',
            ],
            [
                'nama_menu' => 'Steak Master',
                'kategori' => 'makanan',
                'sub_kategori' => 'Spesial & Menu Baru',
                'harga' => 35000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Steak krispi lezat disajikan dengan pilihan saus: Brown Sauce, Blackpepper Sauce, atau BBQ Sauce.',
            ],
            [
                'nama_menu' => 'Nila Saos',
                'kategori' => 'makanan',
                'sub_kategori' => 'Spesial & Menu Baru',
                'harga' => 40000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Ikan nila goreng renyah disiram kuah saus asam manis pedas berlimpah sayuran.',
            ],
            [
                'nama_menu' => 'Salad Buah Master',
                'kategori' => 'makanan',
                'sub_kategori' => 'Spesial & Menu Baru',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Potongan buah-buahan segar dingin berbalur mayones creamy manis bertabur keju parut melimpah.',
            ],
            [
                'nama_menu' => 'Jamur Krispi',
                'kategori' => 'makanan',
                'sub_kategori' => 'Spesial & Menu Baru',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Jamur goreng tepung renyah keemasan dengan saus cocolan cabai gurih.',
            ],
            [
                'nama_menu' => 'Ayam Geprek + Jengkol dan Ikan Asin',
                'kategori' => 'makanan',
                'sub_kategori' => 'Spesial & Menu Baru',
                'harga' => 40000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kombinasi juara ayam geprek pedas nampol dipadu jengkol legit dan renyahnya ikan asin gurih.',
            ],
            [
                'nama_menu' => 'Jengkol Ikan Teri',
                'kategori' => 'makanan',
                'sub_kategori' => 'Spesial & Menu Baru',
                'harga' => 25000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Jengkol pulen empuk dimasak sambal gurih harum dengan taburan ikan teri medan renyah.',
            ],

            // ==========================================
            // 7. MAKANAN: CEMILAN (HALAMAN 2)
            // ==========================================
            [
                'nama_menu' => 'Sempolet',
                'kategori' => 'makanan',
                'sub_kategori' => 'Cemilan',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Sup bubur sagu khas Melayu gurih berpadu daun pakis/kangkung dan rempah tradisional.',
            ],
            [
                'nama_menu' => 'Bakso Goreng',
                'kategori' => 'makanan',
                'sub_kategori' => 'Cemilan',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Bakso goreng renyah gurih di luar empuk di dalam disajikan dengan saus sambal cocol.',
            ],
            [
                'nama_menu' => 'Pisang Coklat',
                'kategori' => 'makanan',
                'sub_kategori' => 'Cemilan',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Pisang manis goreng krispi disiram limpahan susu kental manis coklat lumer.',
            ],
            [
                'nama_menu' => 'Kentang Goreng',
                'kategori' => 'makanan',
                'sub_kategori' => 'Cemilan',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'French fries renyah keemasan ditaburi bumbu gurih disajikan dengan saus tomat/sambal.',
            ],
            [
                'nama_menu' => 'Naget Goreng',
                'kategori' => 'makanan',
                'sub_kategori' => 'Cemilan',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Nugget ayam pilihan digoreng renyah disajikan hangat untuk teman ngobrol.',
            ],
            [
                'nama_menu' => 'Tempe Goreng Tepung',
                'kategori' => 'makanan',
                'sub_kategori' => 'Cemilan',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Tempe mendoan tepung bumbu ketumbar gurih renyah dengan cabai rawit hijau.',
            ],
            [
                'nama_menu' => 'Sosis Goreng',
                'kategori' => 'makanan',
                'sub_kategori' => 'Cemilan',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Sosis sapi goreng mekar renyah disajikan dengan cocolan saus mayones dan sambal.',
            ],
            [
                'nama_menu' => 'Mix (Naget, Kentang, Sosis)',
                'kategori' => 'makanan',
                'sub_kategori' => 'Cemilan',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Cemilan komplit porsi sharing berisi paduan nugget, kentang goreng krispi, dan sosis gurih.',
            ],

            // ==========================================
            // 8. MINUMAN: COFFEE (HALAMAN 4)
            // ==========================================
            [
                'nama_menu' => 'Americano',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Espresso murni aromatik dipadu air mineral (Pilihan Hot Rp 15.000 / Ice Rp 18.000).',
            ],
            [
                'nama_menu' => 'Caffe Latte',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Perpaduan seimbang espresso kaya rasa dan steamed milk lembut (Pilihan Hot Rp 20.000 / Ice Rp 22.000).',
            ],
            [
                'nama_menu' => 'Cappuccino',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kopi espresso klasik dengan busa susu tebal lembut di atasnya (Pilihan Hot Rp 20.000 / Ice Rp 22.000).',
            ],
            [
                'nama_menu' => 'V60 Manual Brew',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Seduh manual pour-over V60 menghasilkan karakter rasa kopi bersih dan aromatik (Hot / Ice).',
            ],
            [
                'nama_menu' => 'Vietnam Drip',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Ekstraksi kopi tetes tradisional Vietnam di atas susu kental manis legit (Hot / Ice).',
            ],
            [
                'nama_menu' => 'Coffee Aren Master',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kopi susu khas racikan Master Cafe dengan gula aren murni pilihan yang harum dan legit (Hot / Ice).',
            ],
            [
                'nama_menu' => 'Vanilla Latte',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kopi susu espresso lembut berpadu sirup vanilla manis harum (Hot / Ice).',
            ],
            [
                'nama_menu' => 'Kopi Sanger',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kopi sanger khas Aceh tarikan mantap berpadu susu kental manis pas di lidah (Hot / Ice).',
            ],
            [
                'nama_menu' => 'Hazelnut Latte',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Espresso latte creamy dengan aroma kacang hazelnut yang gurih manis harum (Hot / Ice).',
            ],
            [
                'nama_menu' => 'Caramel Latte',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Espresso latte dengan siraman saus karamel legit manis harum (Hot / Ice).',
            ],
            [
                'nama_menu' => 'Kopi Ginseng',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 13000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kopi hitam stamina beraroma ekstrak ginseng hangat menyehatkan tubuh (Hot / Ice).',
            ],
            [
                'nama_menu' => 'Kopi Susu',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 13000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kopi hitam tradisional dipadu manis legitnya susu kental manis (Hot / Ice).',
            ],
            [
                'nama_menu' => 'Kopi O',
                'kategori' => 'minuman',
                'sub_kategori' => 'Coffee',
                'harga' => 8000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kopi hitam pekat manis tradisional khas kedai kopi Melayu.',
            ],

            // ==========================================
            // 9. MINUMAN: VARIAN TEH (HALAMAN 4 & 5)
            // ==========================================
            [
                'nama_menu' => 'Es Teh',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Teh',
                'harga' => 7000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Seduhan teh melati asli disajikan dingin segar pelepas dahaga.',
            ],
            [
                'nama_menu' => 'Lychee Tea',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Teh',
                'harga' => 16000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Teh seduh wangi berpadu manis harum buah leci segar dingin.',
            ],
            [
                'nama_menu' => 'Es Teh Melon',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Teh',
                'harga' => 12000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Teh segar dingin dengan sirup buah melon manis harum semerbak.',
            ],
            [
                'nama_menu' => 'Manggo Tea',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Teh',
                'harga' => 10000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Kesegaran teh dingin dengan aroma buah mangga tropis yang manis segar.',
            ],
            [
                'nama_menu' => 'Es Teh Susu',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Teh',
                'harga' => 12000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Teh seduh pekat berpadu gurihnya susu kental manis disajikan dingin.',
            ],
            [
                'nama_menu' => 'Es Teh Markisa',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Teh',
                'harga' => 12000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Sensasi asam manis buah markisa segar berpadu teh dingin pelepas dahaga.',
            ],
            [
                'nama_menu' => 'Teh Tarik',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Teh',
                'harga' => 12000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Teh susu ditarik tradisional berbusa lembut dengan citarasa otentik gurih manis.',
            ],
            [
                'nama_menu' => 'Lemon Tea',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Teh',
                'harga' => 13000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Perpaduan teh seduh dan perasan jeruk lemon asli segar (Hot Rp 13.000 / Ice Rp 15.000).',
            ],
            [
                'nama_menu' => 'Teh Jahe',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Teh',
                'harga' => 6000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Seduhan teh rempah jahe geprek hangat menyegarkan tubuh (Hot Rp 6.000 / Ice Rp 8.000).',
            ],

            // ==========================================
            // 10. MINUMAN: VARIAN MOJITO (HALAMAN 5)
            // ==========================================
            [
                'nama_menu' => 'Mojito Melon',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Mojito',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Mocktail soda dingin beraroma melon manis dengan kesegaran daun mint asli.',
            ],
            [
                'nama_menu' => 'Mojito Leci',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Mojito',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Minuman bersoda segar dengan sirup leci manis dan daun mint dingin.',
            ],
            [
                'nama_menu' => 'Blue Ocean Lemon',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Mojito',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Soda biru laut eksotis berpadu perasan lemon segar asam manis dingin.',
            ],
            [
                'nama_menu' => 'Butter Fly Lemon',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Mojito',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Gradasi warna ungu cantik dari ekstrak bunga telang berpadu kesegaran lemon bersoda.',
            ],

            // ==========================================
            // 11. MINUMAN: VARIAN JUS (HALAMAN 5)
            // ==========================================
            [
                'nama_menu' => 'Jus Mangga',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Jus',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Jus buah mangga manis matang alami disajikan dingin kental menyegarkan.',
            ],
            [
                'nama_menu' => 'Jus Jeruk',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Jus',
                'harga' => 12000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Perasan jeruk peras murni kaya vitamin C disajikan dingin segar alami.',
            ],
            [
                'nama_menu' => 'Jus Alpukat',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Jus',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Alpukat mentega lembut kental berpadu lelehan susu kental manis coklat gurih.',
            ],
            [
                'nama_menu' => 'Jus Jagung',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Jus',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Jus jagung manis khas Master Cafe yang creamy, kental, dan harum gurih.',
            ],
            [
                'nama_menu' => 'Jus Apel',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Jus',
                'harga' => 15000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Jus buah apel segar dengan manis alami yang menyegarkan dahaga.',
            ],
            [
                'nama_menu' => 'Jus Wortel',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Jus',
                'harga' => 12000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Jus wortel murni segar dan sehat kaya akan nutrisi dan vitamin A.',
            ],
            [
                'nama_menu' => 'Jus Buah Naga',
                'kategori' => 'minuman',
                'sub_kategori' => 'Varian Jus',
                'harga' => 12000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Jus buah naga merah segar kaya antioksidan dengan rasa manis alami dingin.',
            ],

            // ==========================================
            // 12. MINUMAN: NON-COFFEE & BLEND (HAL 4 & 5)
            // ==========================================
            [
                'nama_menu' => 'Cookie & Cream',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Blended susu lembut berpadu remahan biskuit Oreo manis legit gurih.',
            ],
            [
                'nama_menu' => 'Vanilla Blend',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Minuman susu vanilla blend lembut beraroma harum manis menenangkan.',
            ],
            [
                'nama_menu' => 'Choco Brown Sugar',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Coklat pekat premium dipadu legitnya gula aren murni aromatik.',
            ],
            [
                'nama_menu' => 'Choco Milk',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Coklat susu klasik kental gurih manis favorit sepanjang masa.',
            ],
            [
                'nama_menu' => 'Tiramisu Blend',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Minuman rasa tiramisu khas Italia dengan aroma kopi dan keju manis lembut.',
            ],
            [
                'nama_menu' => 'Red Velvet',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Minuman red velvet manis creamy dengan warna merah memikat dan rasa khas.',
            ],
            [
                'nama_menu' => 'Capucino Blend',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Minuman kopi cappuccino blended dingin berbusa lembut yang creamy.',
            ],
            [
                'nama_menu' => 'Dark Choco',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Coklat hitam pekat dengan paduan rasa manis dan pahit kakao yang seimbang.',
            ],
            [
                'nama_menu' => 'Milk Tea Brown Sugar',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Teh susu wangi dipadu sirup brown sugar legit bercitarasa khas.',
            ],
            [
                'nama_menu' => 'Bubble Gum',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Minuman rasa permen karet manis ceria berwarna biru muda menarik.',
            ],
            [
                'nama_menu' => 'Brownsugar Mix Taro',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Paduan rasa taro ungu manis lembut dengan sirup brown sugar legit gurih.',
            ],
            [
                'nama_menu' => 'Taro Blend',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Minuman susu rasa talas taro ungu bertekstur creamy manis harum.',
            ],
            [
                'nama_menu' => 'Choco Hazelnut',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 20000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Perpaduan coklat pekat dan gurihnya kacang hazelnut ala kafe premium.',
            ],
            [
                'nama_menu' => 'Greentea Matcha',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 18000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Teh hijau matcha Jepang berpadu susu segar lembut beraroma harum.',
            ],
            [
                'nama_menu' => 'Milo',
                'kategori' => 'minuman',
                'sub_kategori' => 'Non-Coffee & Blend',
                'harga' => 13000,
                'is_dynamic_price' => false,
                'deskripsi' => 'Minuman coklat malt Milo kaya energi disukai segala usia (Hot Rp 13.000 / Ice Rp 15.000).',
            ],
        ];

        foreach ($menus as $item) {
            $existing = Menu::where('nama_menu', $item['nama_menu'])->first();
            if ($existing) {
                // Update kategori, sub_kategori, harga, deskripsi tanpa menimpa foto jika sudah ada foto
                $existing->update([
                    'kategori' => strtolower($item['kategori']),
                    'sub_kategori' => $item['sub_kategori'],
                    'harga' => $item['harga'],
                    'is_dynamic_price' => $item['is_dynamic_price'] ?? false,
                    'deskripsi' => $item['deskripsi'],
                    'is_available' => true,
                    'stok' => 999,
                ]);
            } else {
                Menu::create([
                    'nama_menu' => $item['nama_menu'],
                    'kategori' => strtolower($item['kategori']),
                    'sub_kategori' => $item['sub_kategori'],
                    'harga' => $item['harga'],
                    'is_dynamic_price' => $item['is_dynamic_price'] ?? false,
                    'deskripsi' => $item['deskripsi'],
                    'is_available' => true,
                    'stok' => 999,
                    'image' => null, // Dibiarkan null agar menampilkan logo placeholder Master Cafe sampai user mengunggah foto
                ]);
            }
        }
    }
}
